# ------------------------
# 🔹 ConfigMap
# ------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
  namespace: aggregator-ns
data:
  # Comment AS_ISSUER out if you do not need UMA Authorization
  aggregator_external_host: "$MINIKUBE-IP"   # Set automatically during minikube-deploy
  # as_issuer: "$UMA-IP"                     # Replace with your auth server if needed
